name: MiniFactions
version: '${project.version}'
main: dansplugins.minifactions.MiniFactions
api-version: 1.13

commands:
  minifactions:
  mf:
  factions:
  f:

permissions:
  mf.help:
    default: true