name: MedievalFactionsRedesigned
version: v5.0-alpha-v0.1
main: dansplugins.medievalfactionsredesign.MedievalFactions
api-version: 1.13

commands:
  medievalfactions:
  mf:
  factions:
  f:

permissions:
  mf.help:
    default: true