name: MiniFactions
version: v5.0-alpha-v0.1
main: dansplugins.minifactionsredesign.MiniFactions
api-version: 1.13

commands:
  minifactions:
  mf:
  factions:
  f:

permissions:
  mf.help:
    default: true